---
settings:
  name: NetApp solutions for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Solutions pour SAP
    url: "/index.html"
  - title: Quoi de neuf
    url: "/whats-new.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
