---
sidebar: sidebar 
permalink: sap-dr-videos.html 
summary: Série de vidéos et démonstrations traitant de la sauvegarde, de la restauration et de la reprise après incident SAP 
keywords: netapp, solutions, SAP, backup, restore, disaster recover, dr, videos, demos 
---
= Vidéos et démonstrations sur la sauvegarde, la restauration et la reprise après incident pour SAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Présentation des vidéos et démonstrations illustrant la sauvegarde, la restauration et la reprise après incident SAP.



=== Vidéos et démonstrations sur la sauvegarde, la restauration et la reprise après incident pour SAP

* link:https://media.netapp.com/video-detail/6b94b9c3-0862-5da8-8332-5aa1ffe86419/disaster-recovery-options-for-sap-hana["Options de reprise après incident pour SAP HANA"^]


.Installation et configuration du plug-in DB2, sauvegarde de la base de données DB2
video::66c87afd-ca53-4af1-8bd8-b2b900c1fb0f[panopto,width=360]
.Restauration et récupération de la base de données DB2
video::3a82e561-e5a2-4a23-9465-b2b900c1fac5[panopto,width=360]
.Plug-in installation ASE, plug-in Configuration ASE, sauvegarde de la base de données ASE
video::079554d1-452c-42e5-95f6-b2b900c1fa86[panopto,width=360]
.Restauration et récupération de la base de données ASE
video::0aba8433-e0d0-4c40-be0a-b2b900c1fb54[panopto,width=360]