---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'netapp, solutions, sap, sap hana, what"s new, updates, change log' 
summary: Journal des modifications récentes apportées aux solutions NetApp pour les garanties SAP. 
---
= Quelles sont les nouveautés des solutions NetApp pour SAP ?
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés des solutions pour SAP.



== 2 décembre 2025

Nouvelle solution :link:https://docs.netapp.com/us-en/netapp-solutions-sap/backup/hana-sc-generic-scope.html["Sauvegarde et restauration SAP HANA avec SnapCenter"^]

Cette solution fournit les meilleures pratiques pour la protection des données SAP HANA avec NetApp SnapCenter, couvrant les directives de configuration et d'exploitation de SnapCenter pour la protection des systèmes SAP HANA sur les systèmes ONTAP AFF et ASA , Azure NetApp Files et Amazon FSx pour ONTAP.



== 12 novembre 2025

Nouvelle solutionlink:https://docs.netapp.com/us-en/netapp-solutions-sap/bp/kvm-hana-introduction.html["SAP HANA avec SUSE KVM et stockage NetApp"^] :

Déploiement de SAP HANA mono-hôte sur SUSE KVM utilisant le stockage NetApp avec des interfaces réseau SR-IOV et un accès au stockage NFS ou FCP.



== 18 août 2025

Le site NetApp Solutions est désormais lelink:https://docs.netapp.com/us-en/netapp-solutions-family/index.html["Famille de solutions NetApp"^] , qui comprend les sites suivants :

* link:https://docs.netapp.com/us-en/netapp-solutions-ai/index.html["Solutions d'intelligence artificielle NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-containers/index.html["Solutions de conteneurs NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-dataops/index.html["Solutions de gestion de données NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-databases/index.html["Solutions de base de données NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/index.html["Solutions de cloud public et hybride NetApp"^]
* Solutions NetApp pour SAP
* link:https://docs.netapp.com/us-en/netapp-solutions-virtualization/index.html["Solutions de virtualisation NetApp"^]

