---
sidebar: sidebar 
permalink: backup/amazon-fsx-overview.html 
keywords: tr4926, 4926, introduction, overview 
summary: 'Dans ce rapport technique, vous bénéficiez des meilleures pratiques en matière de protection des données SAP HANA sur Amazon FSX pour NetApp ONTAP et NetApp SnapCenter. Ce document présente les concepts relatifs à SnapCenter, les recommandations sur la configuration et les workflows d"exploitation, y compris la configuration, les opérations de sauvegarde et les opérations de restauration et de reprise.' 
---
= Tr-4926 : SAP HANA sur Amazon FSX pour NetApp ONTAP - sauvegarde et restauration avec SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nils Bauer, NetApp

Dans ce rapport technique, vous bénéficiez des meilleures pratiques en matière de protection des données SAP HANA sur Amazon FSX pour NetApp ONTAP et NetApp SnapCenter. Ce document présente les concepts relatifs à SnapCenter, les recommandations sur la configuration et les workflows d'exploitation, y compris la configuration, les opérations de sauvegarde et les opérations de restauration et de reprise.

Les entreprises ont besoin aujourd'hui d'une disponibilité continue et sans interruption pour leurs applications SAP. Elles espèrent obtenir des niveaux de performance prévisibles dans un contexte où les volumes de données ne cessent d'augmenter et nécessitent des tâches de maintenance de routine, comme les sauvegardes système. Le fait d'effectuer des sauvegardes de bases de données SAP est une tâche critique qui peut avoir un impact significatif sur les performances du système SAP de production.

Les fenêtres de sauvegarde diminuent alors que le volume des données à sauvegarder augmente. Par conséquent, il est difficile de trouver un moment où vous pouvez effectuer des sauvegardes avec un impact minimal sur les processus de l'entreprise. Le temps nécessaire à la restauration et à la restauration des systèmes SAP pose problème, car les temps d'indisponibilité des systèmes de production et hors production SAP doivent être réduits de manière à réduire les coûts pour l'entreprise.

link:amazon-fsx-backup-and-recovery-using-amazon-fsx-for-ontap.html["Ensuite : sauvegarde et restauration avec Amazon FSX pour ONTAP."]
