---
sidebar: sidebar 
permalink: backup/amazon-fsx-configure-replication-relationships-on-fsx-for-ontap-file-systems.html 
keywords: Peer FSx, ontap file system, svm, target volume, snapmirror, 
summary: Cette section décrit comment peer-to-peer FSX pour les systèmes de fichiers ONTAP, peer-to-peer, créer un volume cible, créer une règle SnapMirror, créer une relation SnapMirror et initialiser SnapMirror. 
---
= Configurer les relations de réplication sur FSX pour les systèmes de fichiers ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour plus d'informations sur les options de configuration de SnapMirror, consultez la documentation ONTAP à l'adresse https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-replication-workflow-concept.html["Workflow de réplication SnapMirror (netapp.com)"^].

* FSX source pour système de fichiers ONTAP : `FsxId00fa9e3c784b6abbb`
* SVM source : `sapcc-hana-svm`
* Cible FSX pour système de fichiers ONTAP : `FsxId05f7f00af49dc7a3e`
* SVM cible : `sapcc-backup-target-zone5`




== Peer FSX pour les systèmes de fichiers ONTAP

....
FsxId00fa9e3c784b6abbb::> network interface show -role intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
FsxId00fa9e3c784b6abbb
            inter_1      up/up    10.1.1.57/24       FsxId00fa9e3c784b6abbb-01
                                                                   e0e     true
            inter_2      up/up    10.1.2.7/24        FsxId00fa9e3c784b6abbb-02
                                                                   e0e     true
2 entries were displayed.
....
....
FsxId05f7f00af49dc7a3e::> network interface show -role intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
FsxId05f7f00af49dc7a3e
            inter_1      up/up    10.1.2.144/24      FsxId05f7f00af49dc7a3e-01
                                                                   e0e     true
            inter_2      up/up    10.1.2.69/24       FsxId05f7f00af49dc7a3e-02
                                                                   e0e     true
2 entries were displayed.
....
....
FsxId05f7f00af49dc7a3e::> cluster peer create -address-family ipv4 -peer-addrs 10.1.1.57, 10.1.2.7
Notice: Use a generated passphrase or choose a passphrase of 8 or more characters. To ensure the authenticity of the peering relationship, use a phrase or sequence of characters that would be hard to guess.
Enter the passphrase:
Confirm the passphrase:
Notice: Now use the same passphrase in the "cluster peer create" command in the other cluster.
....

NOTE: `peer-addrs` Les adresses IP de cluster du cluster cible sont-elles des.

....
FsxId00fa9e3c784b6abbb::>  cluster peer create -address-family ipv4 -peer-addrs  10.1.2.144, 10.1.2.69
Notice: Use a generated passphrase or choose a passphrase of 8 or more characters. To ensure the authenticity of the peering relationship, use a
        phrase or sequence of characters that would be hard to guess.
Enter the passphrase:
Confirm the passphrase:
FsxId00fa9e3c784b6abbb::>
FsxId00fa9e3c784b6abbb::> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
FsxId05f7f00af49dc7a3e    1-80-000011           Available      ok
....


== SVM homologues

....
FsxId05f7f00af49dc7a3e::> vserver peer create -vserver sapcc-backup-target-zone5 -peer-vserver sapcc-hana-svm -peer-cluster FsxId00fa9e3c784b6abbb -applications snapmirror
Info: [Job 41] 'vserver peer create' job queued
....
....
FsxId00fa9e3c784b6abbb::> vserver peer accept -vserver sapcc-hana-svm  -peer-vserver sapcc-backup-target-zone5
Info: [Job 960] 'vserver peer accept' job queued
....
....
FsxId05f7f00af49dc7a3e::> vserver peer show
            Peer        Peer                           Peering        Remote
Vserver     Vserver     State        Peer Cluster      Applications   Vserver
----------- ----------- ------------ ----------------- -------------- ---------
sapcc-backup-target-zone5
            peer-source-cluster
                        peered       FsxId00fa9e3c784b6abbb
                                                       snapmirror     sapcc-hana-svm
....


== Créer un volume cible

Vous devez créer le volume cible avec le type `DP` pour le marquer comme cible de réplication.

....
FsxId05f7f00af49dc7a3e::> volume create -vserver sapcc-backup-target-zone5  -volume PFX_data_mnt00001 -aggregate aggr1 -size 100GB -state online -policy default -type DP -autosize-mode grow_shrink -snapshot-policy none -foreground true -tiering-policy all -anti-ransomware-state disabled
[Job 42] Job succeeded: Successful
....


== Créer une règle SnapMirror

La règle SnapMirror et la règle ajoutée définissent la rétention et l'étiquette SnapMirror pour identifier les snapshots à répliquer. Lorsque vous créez la stratégie SnapCenter ultérieurement, vous devez utiliser le même libellé.

....
FsxId05f7f00af49dc7a3e::> snapmirror policy create -policy snapcenter-policy -tries 8 -transfer-priority normal -ignore-atime false -restart always -type vault -vserver sapcc-backup-target-zone5
....
....
FsxId05f7f00af49dc7a3e::> snapmirror policy add-rule -vserver sapcc-backup-target-zone5  -policy snapcenter-policy -snapmirror-label snapcenter -keep 14
....
....
FsxId00fa9e3c784b6abbb::> snapmirror policy showVserver Policy             Policy Number         Transfer
Name    Name               Type   Of Rules Tries Priority Comment
------- ------------------ ------ -------- ----- -------- ----------
FsxId00fa9e3c784b6abbb
        snapcenter-policy  vault         1     8  normal  -
  SnapMirror Label: snapcenter                         Keep:      14
                                                 Total Keep:      14
....


== Créer une relation SnapMirror

Maintenant la relation entre les volumes source et cible est définie, ainsi que le type XDP et la règle que nous avons créée précédemment.

....
FsxId05f7f00af49dc7a3e::> snapmirror create -source-path sapcc-hana-svm:PFX_data_mnt00001 -destination-path sapcc-backup-target-zone5:PFX_data_mnt00001 -vserver sapcc-backup-target-zone5 -throttle unlimited -identity-preserve false -type XDP -policy snapcenter-policy
Operation succeeded: snapmirror create for the relationship with destination "sapcc-backup-target-zone5:PFX_data_mnt00001".
....


== Initialiser SnapMirror

Avec cette commande, la réplication initiale démarre. Il s'agit d'un transfert complet de toutes les données depuis le volume source vers le volume cible.

....
FsxId05f7f00af49dc7a3e::> snapmirror initialize -destination-path sapcc-backup-target-zone5:PFX_data_mnt00001 -source-path sapcc-hana-svm:PFX_data_mnt00001
Operation is queued: snapmirror initialize of destination "sapcc-backup-target-zone5:PFX_data_mnt00001".
....
Vous pouvez vérifier l'état de la réplication avec `snapmirror show` commande.

....
FsxId05f7f00af49dc7a3e::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
sapcc-hana-svm:PFX_data_mnt00001
            XDP  sapcc-backup-target-zone5:PFX_data_mnt00001
                              Uninitialized
                                      Transferring   1009MB    true    02/24 12:34:28
....
....
FsxId05f7f00af49dc7a3e::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
sapcc-hana-svm:PFX_data_mnt00001
            XDP  sapcc-backup-target-zone5:PFX_data_mnt00001
                              Snapmirrored
                                      Idle           -         true    -
....