---
sidebar: sidebar 
permalink: backup/anf-cba-overview.html 
keywords: tr4959, 4959, overview, introduction 
summary: 'Dans ce rapport technique, nous vous proposons les bonnes pratiques de protection des données SAP HANA sur Azure NetApp Files (ANF) avec NetApp BlueXP Cloud Backup pour applications (CBA). Le document traite des concepts CBA, des meilleures pratiques de configuration et des descriptions des flux de travail opérationnels pour les opérations de sauvegarde, de restauration et de récupération.' 
---
= Tr-4959 : SAP HANA sur ANF : sauvegarde et restauration avec Cloud Backup pour applications
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nils Bauer, NetApp

[role="lead"]
Dans ce rapport technique, nous vous proposons les bonnes pratiques de protection des données SAP HANA sur Azure NetApp Files (ANF) avec NetApp BlueXP Cloud Backup pour applications (CBA). Le document traite des concepts CBA, des meilleures pratiques de configuration et des descriptions des flux de travail opérationnels pour les opérations de sauvegarde, de restauration et de récupération.

Les entreprises ont besoin aujourd'hui d'une disponibilité continue et sans interruption pour leurs applications SAP. Elles espèrent obtenir des niveaux de performance prévisibles dans un contexte où les volumes de données et les tâches de maintenance de routine, telles que les sauvegardes système, ne cessent de croître. Le processus de sauvegarde des bases de données SAP est une tâche critique qui peut affecter les performances du système SAP de production.

Les fenêtres de sauvegarde diminuent alors que le volume des données à sauvegarder augmente. Par conséquent, il est difficile de trouver un moment où vous pouvez effectuer des sauvegardes avec un impact minimal sur les processus métier. Le temps nécessaire à la restauration et à la restauration des systèmes SAP pose problème, car les temps d'indisponibilité des systèmes de production et hors production SAP doivent être réduits de manière à réduire les coûts pour l'entreprise.

link:anf-cba-backup-and-recovery-using-azure-netapp-files.html["Suivant : sauvegarde et restauration avec Azure NetApp Files."]
