---
sidebar: sidebar 
permalink: backup/fsxn-additional-info.html 
keywords:  
summary:  
---
= Où trouver des informations complémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Guide de l'utilisateur FSX pour NetApp ONTAP — Qu'est-ce qu'Amazon FSX pour NetApp ONTAP ?
+
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[]

* Page des ressources SnapCenter
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx["https://www.netapp.com/us/documentation/snapcenter-software.aspx"]

* Documentation du logiciel SnapCenter
+
https://docs.netapp.com/us-en/snapcenter/index.html["https://docs.netapp.com/us-en/snapcenter/index.html"]

* Tr-4667 : automatisation des opérations de copie système et de clonage SAP HANA avec SnapCenter
+
link:../lifecycle/sc-copy-clone-introduction.html["Automatisation des opérations de copie et de clonage du système SAP HANA avec SnapCenter"]

* Tr-4719 : réplication système SAP HANA : sauvegarde et restauration avec SnapCenter
+
link:hana-sr-scs-system-replication-overview.html["Sauvegarde et restauration avec SnapCenter"]





== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Mai 2022 | Version initiale. 
|===