---
sidebar: sidebar 
permalink: backup/hana-br-scs-additional-info.html 
keywords:  
summary:  
---
= Où trouver des informations supplémentaires et l'historique des versions
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Page Ressources SnapCenter
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx["https://www.netapp.com/us/documentation/snapcenter-software.aspx"^]

* Documentation du logiciel SnapCenter
+
https://docs.netapp.com/us-en/snapcenter/index.html["https://docs.netapp.com/us-en/snapcenter/index.html"^]

* Tr-4667 : automatisation des copies du système SAP à l'aide de SnapCenter
+
link:../lifecycle/sc-copy-clone-introduction.html["Automatisation des copies du système SAP à l'aide de SnapCenter"]

* Tr-4719 : réplication, sauvegarde et restauration système SAP HANA avec SnapCenter
+
link:hana-sr-scs-system-replication-overview.html["Réplication système, sauvegarde et restauration SAP HANA avec SnapCenter"]

* Tr-4018 : intégration des systèmes NetApp ONTAP à la gestion du paysage SAP
+
https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf"^]

* Tr-4646 : reprise après incident de SAP HANA avec réplication du stockage
+
https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf["https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf"^]





== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Juillet 2017  a| 
* Version initiale.




| Version 1.1 | Septembre 2017  a| 
* Ajout de la section "Configuration avancée et réglage".
* Corrections mineures.




| Version 2.0 | Mars 2018  a| 
* Mises à jour relatives à SnapCenter 4.0 :
Nouvelle ressource de volume de données
Amélioration du fonctionnement de Single File SnapRestore




| Version 3.0 | Janvier 2020  a| 
* Ajout de la section « concepts et meilleures pratiques SnapCenter ».
* Mises à jour relatives à SnapCenter 4.3 :
Détection automatique
Restauration et reprise automatisées
Prise en charge de plusieurs locataires MDC HANA
Opération de restauration mutualisée unique




| Version 3.1 | Juillet 2020  a| 
* Mises à jour et corrections mineures :
Prise en charge de NFSv4 avec SnapCenter 4.3.1
Configuration de la communication SSL
Déploiement centralisé de plug-in pour Linux sur IBM Power




| Version 3.2 | Novembre 2020  a| 
* Ajout des privilèges d'utilisateur de base de données requis pour HANA 2.0 SPS5.




| Version 3.3 | Mai 2021  a| 
* Mise à jour de la section de configuration hdbsql SSL.
* Ajout de la prise en charge LVM de Linux.




| Version 3.4 | Août 2021  a| 
* Ajout de la description de la configuration de désactivation de la détection automatique.




| Version 3.5 | Février 2022  a| 
* Mises à jour mineures pour couvrir SnapCenter 4.6 et la prise en charge de la détection automatique pour les systèmes HANA compatibles avec la réplication du système.


|===