---
sidebar: sidebar 
permalink: backup/hana-dr-anf-prepare-target-host_01.html 
keywords: prepare, target, host, sap, hana, azure, log, volume, users, ports, configure, file, system 
summary: Cette section décrit les étapes de préparation requises au niveau du serveur utilisé pour le basculement de reprise après sinistre. 
---
= Préparez l'hôte cible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette section décrit les étapes de préparation requises au niveau du serveur utilisé pour le basculement de reprise après sinistre.

En fonctionnement normal, l'hôte cible est généralement utilisé à d'autres fins, par exemple comme système d'assurance qualité ou de test HANA. Par conséquent, la plupart des étapes décrites doivent être effectuées lors de l'exécution du test de basculement. D'autre part, les fichiers de configuration appropriés, comme `/etc/fstab` et `/usr/sap/sapservices`, peut être préparé puis mis en production en copiant simplement le fichier de configuration. La procédure de basculement de reprise après sinistre garantit que les fichiers de configuration préparés appropriés sont correctement configurés.

La préparation de l'hôte cible comprend également l'arrêt du système d'assurance qualité ou de test HANA, ainsi que l'arrêt de tous les services à l'aide de `systemctl stop sapinit`.



== Nom d'hôte et adresse IP du serveur cible

Le nom d'hôte du serveur cible doit être identique au nom d'hôte du système source. L'adresse IP peut être différente.


NOTE: Une clôture correcte du serveur cible doit être établie de sorte qu'il ne puisse pas communiquer avec d'autres systèmes. Si une clôture correcte n'est pas en place, le système de production cloné peut échanger des données avec d'autres systèmes de production, ce qui entraîne une corruption logique des données.



== Installez le logiciel requis

Le logiciel de l'agent hôte SAP doit être installé sur le serveur cible. Pour plus d'informations, reportez-vous à la section https://help.sap.com/viewer/9f03f1852ce94582af41bb49e0a667a7/103/en-US["Agent hôte SAP"^] Sur le portail d'aide SAP.


NOTE: Si l'hôte est utilisé comme système d'assurance qualité ou de test HANA, le logiciel de l'agent hôte SAP est déjà installé.



== Configuration des utilisateurs, des ports et des services SAP

Les utilisateurs et groupes requis pour la base de données SAP HANA doivent être disponibles sur le serveur cible. En général, la gestion centralisée des utilisateurs est utilisée ; aucune étape de configuration n'est donc nécessaire sur le serveur cible. Les ports requis pour la base de données HANA doivent être configurés sur les hôtes cibles. La configuration peut être copiée à partir du système source en copiant `/etc/services` vers le serveur cible.

Les entrées de services SAP requises doivent être disponibles sur l'hôte cible. La configuration peut être copiée à partir du système source en copiant `/usr/sap/sapservices` vers le serveur cible. Le résultat suivant montre les entrées requises pour la base de données SAP HANA utilisée dans la configuration de laboratoire.

....
vm-pr1:~ # cat /usr/sap/sapservices
#!/bin/sh
LD_LIBRARY_PATH=/usr/sap/PR1/HDB01/exe:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH;/usr/sap/PR1/HDB01/exe/sapstartsrv pf=/usr/sap/PR1/SYS/profile/PR1_HDB01_vm-pr1 -D -u pr1adm
limit.descriptors=1048576
....


== Préparez le volume du journal HANA

Comme le volume de journal HANA ne fait pas partie de la réplication, un volume de journal vide doit exister sur l'hôte cible. Le volume de journalisation doit inclure les mêmes sous-répertoires que le système HANA source.

....
vm-pr1:~ # ls -al /hana/log/PR1/mnt00001/
total 16
drwxrwxrwx 5 root   root   4096 Feb 19 16:20 .
drwxr-xr-x 3 root   root     22 Feb 18 13:38 ..
drwxr-xr-- 2 pr1adm sapsys 4096 Feb 22 10:25 hdb00001
drwxr-xr-- 2 pr1adm sapsys 4096 Feb 22 10:25 hdb00002.00003
drwxr-xr-- 2 pr1adm sapsys 4096 Feb 22 10:25 hdb00003.00003
vm-pr1:~ #
....


== Préparez le volume de sauvegarde des journaux

Comme le système source est configuré avec un volume distinct pour les sauvegardes de journaux HANA, un volume de sauvegarde de journal doit également être disponible au niveau de l'hôte cible. Un volume pour les sauvegardes des journaux doit être configuré et monté sur l'hôte cible.

Si la réplication du volume de sauvegarde des journaux fait partie de la configuration de reprise après incident, le volume de sauvegarde des journaux répliqués est monté sur l'hôte cible, et il n'est pas nécessaire de préparer un volume de sauvegarde de journaux supplémentaire.



== Préparer les montages du système de fichiers

Le tableau suivant présente les conventions de nommage utilisées dans la configuration du laboratoire. Les noms des volumes du site de reprise d'activité sont inclus dans la `/etc/fstab`.

|===
| Volumes HANA PR1 | Volume et sous-répertoires du site de reprise après incident | Point de montage sur l'hôte cible 


| Volume de données | PR1-data-mnt00001-sm-dest | /hana/data/PR1/mnt00001 


| Volume partagé | PR1-shared-sm-dest/shared PR1-shared-sm-dest/usr-sap-PR1 | /hana/shared /usr/sap/PR1 


| Volume de sauvegarde du journal | hanabackup-sm-dest | /hanabackup 
|===

NOTE: Les points de montage de cette table doivent être créés sur l'hôte cible.

Voici les informations requises `/etc/fstab` entrées.

....
vm-pr1:~ # cat /etc/fstab
# HANA ANF DB Mounts
10.0.2.4:/PR1-data-mnt0001-sm-dest /hana/data/PR1/mnt00001 nfs   rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
10.0.2.4:/PR1-log-mnt00001-dr /hana/log/PR1/mnt00001 nfs   rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
# HANA ANF Shared Mounts
10.0.2.4:/PR1-shared-sm-dest/hana-shared /hana/shared nfs rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
10.0.2.4:/PR1-shared-sm-dest/usr-sap-PR1 /usr/sap/PR1 nfs rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
# HANA file and log backup destination
10.0.2.4:/hanabackup-sm-dest    /hanabackup nfs   rw,vers=3,hard,timeo=600,rsize=262144,wsize=262144,nconnect=8,bg,noatime,nolock 0 0
....