---
sidebar: sidebar 
permalink: bp/hana-asa-fc-host-setup.html 
keywords: multipathing, fcp, hba, configure 
summary: 'Avant de configurer l"hôte, les utilitaires hôtes NetApp SAN doivent être téléchargés depuis le site de support NetApp et installés sur les serveurs HANA. La documentation de l"utilitaire hôte contient des informations sur les logiciels supplémentaires qui doivent être installés en fonction du HBA FCP utilisé.' 
---
= Configuration de l'hôte
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Avant de configurer l'hôte, les utilitaires d'hôte SAN de NetApp doivent être téléchargés depuis le http://mysupport.netapp.com/["Support NetApp"^] Et installé sur les serveurs HANA. La documentation de l'utilitaire hôte contient des informations sur les logiciels supplémentaires qui doivent être installés en fonction du HBA FCP utilisé.

Cette documentation contient également des informations sur les configurations multipathing spécifiques à la version de Linux utilisée. Ce document décrit les étapes de configuration requises pour SLES 12 SP1 ou supérieur et RHEL 7. 2 ou ultérieure, comme décrit dans le https://library.netapp.com/ecm/ecm_download_file/ECMLP2547958["Guide d'installation et de configuration de Linux Host Utilities 7.1"^].



=== Configurer les chemins d'accès multiples


NOTE: Les étapes 1 à 6 doivent être exécutées sur tous les hôtes workers et de secours dans une configuration SAP HANA à plusieurs hôtes.

Pour configurer les chemins d'accès multiples, procédez comme suit :

. Exécutez Linux `rescan-scsi-bus.sh -a` Commande sur chaque serveur pour détecter les nouvelles LUN.
. Exécutez le  `sanlun lun show` et vérifiez que tous les LUN requis sont visibles. L'exemple suivant illustre la  `sanlun lun show` Sortie de commande pour un système HANA 2+1 multi-hôtes avec deux LUN de données et deux LUN de journal. La sortie affiche les LUN et les fichiers de périphériques correspondants, tels que LUN.  `FC5_data_mnt00001` et le fichier de l'appareil  `/dev/sdag` Chaque LUN dispose de huit chemins FC de l'hôte aux contrôleurs de stockage.
+
....
sapcc-hana-tst:~ # sanlun lun show
controller(7mode/E-Series)/                                  device          host                  lun
vserver(cDOT/FlashRay)        lun-pathname                   filename        adapter    protocol   size    product
---------------------------------------------------------------------------------------------------------------
svm1                          FC5_log2_mnt00002              /dev/sdbb       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdba       host21     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdaz       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sday       host21     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdax       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdaw       host21     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdav       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdau       host21     FCP        1t      cDOT
svm1                          FC5_log2_mnt00002              /dev/sdat       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdas       host21     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdar       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sdaq       host21     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdap       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdao       host21     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdan       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdam       host21     FCP        1t      cDOT
svm1                          FC5_log2_mnt00002              /dev/sdal       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdak       host20     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdaj       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sdai       host20     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdah       host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdag       host20     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdaf       host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdae       host20     FCP        1t      cDOT
svm1                          FC5_log2_mnt00002              /dev/sdad       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdac       host20     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdab       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sdaa       host20     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdz        host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdy        host20     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdx        host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdw        host20     FCP        1t      cDOT

....
. Exécutez le  `multipath -r` et  `multipath -ll` commande pour obtenir les identifiants mondiaux (WWID) pour les noms de fichiers de périphériques.
+

NOTE: Dans cet exemple, il y a huit LUN.

+
....
sapcc-hana-tst:~ # multipath -r
sapcc-hana-tst:~ # multipath -ll
3600a098038314e63492b59326b4b786d dm-7 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:2 sdaf 65:240 active ready running
  |- 20:0:5:2 sdx  65:112 active ready running
  |- 21:0:4:2 sdav 66:240 active ready running
  `- 21:0:6:2 sdan 66:112 active ready running
3600a098038314e63492b59326b4b786e dm-9 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:4 sdah 66:16  active ready running
  |- 20:0:5:4 sdz  65:144 active ready running
  |- 21:0:4:4 sdax 67:16  active ready running
  `- 21:0:6:4 sdap 66:144 active ready running
3600a098038314e63492b59326b4b786f dm-11 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:6 sdaj 66:48  active ready running
  |- 20:0:5:6 sdab 65:176 active ready running
  |- 21:0:4:6 sdaz 67:48  active ready running
  `- 21:0:6:6 sdar 66:176 active ready running
3600a098038314e63492b59326b4b7870 dm-13 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:8 sdal 66:80  active ready running
  |- 20:0:5:8 sdad 65:208 active ready running
  |- 21:0:4:8 sdbb 67:80  active ready running
  `- 21:0:6:8 sdat 66:208 active ready running
3600a098038314e63532459326d495a64 dm-6 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:1 sdae 65:224 active ready running
  |- 20:0:5:1 sdw  65:96  active ready running
  |- 21:0:4:1 sdau 66:224 active ready running
  `- 21:0:6:1 sdam 66:96  active ready running
3600a098038314e63532459326d495a65 dm-8 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:3 sdag 66:0   active ready running
  |- 20:0:5:3 sdy  65:128 active ready running
  |- 21:0:4:3 sdaw 67:0   active ready running
  `- 21:0:6:3 sdao 66:128 active ready running
3600a098038314e63532459326d495a66 dm-10 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:5 sdai 66:32  active ready running
  |- 20:0:5:5 sdaa 65:160 active ready running
  |- 21:0:4:5 sday 67:32  active ready running
  `- 21:0:6:5 sdaq 66:160 active ready running
3600a098038314e63532459326d495a67 dm-12 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:7 sdak 66:64  active ready running
  |- 20:0:5:7 sdac 65:192 active ready running
  |- 21:0:4:7 sdba 67:64  active ready running
  `- 21:0:6:7 sdas 66:192 active ready running

....
. Modifiez le `/etc/multipath.conf` Et ajoutez les WWID et les noms d'alias.
+

NOTE: L'exemple de résultat montre le contenu du `/etc/multipath.conf` Fichier, qui inclut des noms d'alias pour les quatre LUN d'un système à plusieurs hôtes 2+1. Si aucun fichier multipath.conf n'est disponible, vous pouvez en créer un en exécutant la commande suivante : `multipath -T > /etc/multipath.conf`.

+
....
sapcc-hana-tst:/ # cat /etc/multipath.conf
multipaths {
                multipath {
                wwid    3600a098038314e63492b59326b4b786d
                alias   svm1-FC5_data2_mnt00001
        }
        multipath {
                wwid    3600a098038314e63492b59326b4b786e
                alias   svm1-FC5_data2_mnt00002
        }
        multipath {
                wwid    3600a098038314e63532459326d495a64
                alias   svm1-FC5_data_mnt00001
        }
        multipath {
                wwid    3600a098038314e63532459326d495a65
                alias   svm1-FC5_data_mnt00002
        }
        multipath {
                wwid    3600a098038314e63492b59326b4b786f
                alias   svm1-FC5_log2_mnt00001
        }
        multipath {
                wwid    3600a098038314e63492b59326b4b7870
                alias   svm1-FC5_log2_mnt00002
        }
        multipath {
                wwid    3600a098038314e63532459326d495a66
                alias   svm1-FC5_log_mnt00001
        }
        multipath {
                wwid    3600a098038314e63532459326d495a67
                alias   svm1-FC5_log_mnt00002
        }


}
....
. Exécutez le `multipath -r` commande permettant de recharger la carte du périphérique.
. Vérifiez la configuration en exécutant le `multipath -ll` Commande permettant de répertorier toutes les LUN, les noms d'alias et les chemins actifs et de secours.
+

NOTE: L'exemple de résultat suivant montre les résultats d'un système HANA à plusieurs hôtes 2+1 avec deux données et deux LUN de journalisation.

+
....
sapcc-hana-tst:~ # multipath -ll
hsvm1-FC5_data2_mnt00001 (3600a098038314e63492b59326b4b786d) dm-7 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:2 sdaf 65:240 active ready running
  |- 20:0:5:2 sdx  65:112 active ready running
  |- 21:0:4:2 sdav 66:240 active ready running
  `- 21:0:6:2 sdan 66:112 active ready running
svm1-FC5_data2_mnt00002 (3600a098038314e63492b59326b4b786e) dm-9 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:4 sdah 66:16  active ready running
  |- 20:0:5:4 sdz  65:144 active ready running
  |- 21:0:4:4 sdax 67:16  active ready running
  `- 21:0:6:4 sdap 66:144 active ready running
svm1-FC5_data_mnt00001 (3600a098038314e63532459326d495a64) dm-6 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:1 sdae 65:224 active ready running
  |- 20:0:5:1 sdw  65:96  active ready running
  |- 21:0:4:1 sdau 66:224 active ready running
  `- 21:0:6:1 sdam 66:96  active ready running
svm1-FC5_data_mnt00002 (3600a098038314e63532459326d495a65) dm-8 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:3 sdag 66:0   active ready running
  |- 20:0:5:3 sdy  65:128 active ready running
  |- 21:0:4:3 sdaw 67:0   active ready running
  `- 21:0:6:3 sdao 66:128 active ready running
svm1-FC5_log2_mnt00001 (3600a098038314e63492b59326b4b786f) dm-11 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:6 sdaj 66:48  active ready running
  |- 20:0:5:6 sdab 65:176 active ready running
  |- 21:0:4:6 sdaz 67:48  active ready running
  `- 21:0:6:6 sdar 66:176 active ready running
svm1-FC5_log2_mnt00002 (3600a098038314e63492b59326b4b7870) dm-13 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:8 sdal 66:80  active ready running
  |- 20:0:5:8 sdad 65:208 active ready running
  |- 21:0:4:8 sdbb 67:80  active ready running
  `- 21:0:6:8 sdat 66:208 active ready running
svm1-FC5_log_mnt00001 (3600a098038314e63532459326d495a66) dm-10 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:5 sdai 66:32  active ready running
  |- 20:0:5:5 sdaa 65:160 active ready running
  |- 21:0:4:5 sday 67:32  active ready running
  `- 21:0:6:5 sdaq 66:160 active ready running
svm1-FC5_log_mnt00002 (3600a098038314e63532459326d495a67) dm-12 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:7 sdak 66:64  active ready running
  |- 20:0:5:7 sdac 65:192 active ready running
  |- 21:0:4:7 sdba 67:64  active ready running
  `- 21:0:6:7 sdas 66:192 active ready running

....

