---
sidebar: sidebar 
permalink: bp/hana-fas-nfs-additional-info.html 
keywords: additional, information, fas, nfs, sap, hana 
summary: Pour en savoir plus sur les informations fournies dans ce document, consultez ces documents et/ou sites web. 
---
= Où trouver des informations complémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur les informations fournies dans ce document, consultez ces documents et/ou sites web :

* link:../index.html["Solutions logicielles SAP HANA"^]
* link:../backup/hana-dr-sr-pdf-link.html["Reprise après incident de SAP HANA avec la réplication du stockage"^]
* link:../backup/hana-sc-generic-scope.html["SAP HANA : sauvegarde et restauration avec SnapCenter"^]
* link:../lifecycle/sc-copy-clone-introduction.html["Automatisation des copies de systèmes SAP à l'aide du plug-in SnapCenter SAP HANA"^]
* Centres de documentation NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Matériel de stockage d'entreprise certifié SAP pour SAP HANA
+
https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/["https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/"^]

* Exigences de stockage SAP HANA
+
https://www.sap.com/documents/2024/03/146274d3-ae7e-0010-bca6-c68f7e60039b.html["https://www.sap.com/documents/2024/03/146274d3-ae7e-0010-bca6-c68f7e60039b.html"^]

* FAQ sur l'intégration de SAP HANA Tailored Data Center Integration
+
https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html["https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html"^]

* SAP HANA sur VMware vSphere Wiki
+
https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html["https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html"^]

* Guide des bonnes pratiques de SAP HANA sur VMware vSphere
+
https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper["https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper"^]


