---
sidebar: sidebar 
permalink: bp/hana-fas-fc-host-setup_multiple_hosts.html 
keywords: configure, multipathing, create, lvm, volume, groups, logical, mount, points, file, systems 
summary: La documentation contient également des informations sur les configurations multipathing spécifiques à la version de Linux utilisée. 
---
= Configuration de plusieurs hôtes
:allow-uri-read: 




== Configuration de plusieurs hôtes

[role="lead"]
Ce chapitre décrit la configuration d'un système hôte multiple SAP HANA 2+1 à titre d'exemple.



=== Créez des groupes de volumes LVM et des volumes logiques

. Initialisez toutes les LUN en tant que volume physique.
+
....
pvcreate /dev/mapper/hana-FC5_data_mnt00001
pvcreate /dev/mapper/hana-FC5_data2_mnt00001
pvcreate /dev/mapper/hana-FC5_data_mnt00002
pvcreate /dev/mapper/hana-FC5_data2_mnt00002
pvcreate /dev/mapper/hana-FC5_log_mnt00001
pvcreate /dev/mapper/hana-FC5_log2_mnt00001
pvcreate /dev/mapper/hana-FC5_log_mnt00002
pvcreate /dev/mapper/hana-FC5_log2_mnt00002
....
. Création des groupes de volumes pour chaque partition de données et de journaux
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/hana-FC5_data_mnt00001 /dev/mapper/hana-FC5_data2_mnt00001
vgcreate FC5_data_mnt00002 /dev/mapper/hana-FC5_data_mnt00002 /dev/mapper/hana-FC5_data2_mnt00002
vgcreate FC5_log_mnt00001 /dev/mapper/hana-FC5_log_mnt00001 /dev/mapper/hana-FC5_log2_mnt00001
vgcreate FC5_log_mnt00002 /dev/mapper/hana-FC5_log_mnt00002 /dev/mapper/hana-FC5_log2_mnt00002
....
. Créez un volume logique pour chaque partition de données et de journaux. Utilisez une taille de bande égale au nombre de LUN utilisées par groupe de volumes (dans cet exemple, il y en a deux) et une taille de bande de 256k pour les données et de 64k pour les journaux. SAP ne prend en charge qu'un seul volume logique par groupe de volumes.
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. Analysez les volumes physiques, les groupes de volumes et les groupes de volumes de tous les autres hôtes.


....
modprobe dm_mod
pvscan
vgscan
lvscan
....

NOTE: Si ces commandes ne trouvent pas les volumes, un redémarrage est nécessaire.

Pour monter les volumes logiques, les volumes logiques doivent être activés. Pour activer les volumes, lancer la commande suivante :

....
vgchange -a y
....


=== Créer des systèmes de fichiers

Créez le système de fichiers XFS sur tous les volumes logiques de données et de journaux.

....
mkfs.xfs FC5_data_mnt00001-vol
mkfs.xfs FC5_data_mnt00002-vol
mkfs.xfs FC5_log_mnt00001-vol
mkfs.xfs FC5_log_mnt00002-vol
....


=== Créer des points de montage

Créez les répertoires de points de montage requis et définissez les autorisations sur tous les hôtes de travail et de secours :

....
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00002
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00002
sapcc-hana-tst:/ # mkdir -p /hana/shared
sapcc-hana-tst:/ # chmod –R 777 /hana/log/FC5
sapcc-hana-tst:/ # chmod –R 777 /hana/data/FC5
sapcc-hana-tst:/ # chmod 777 /hana/shared
....


=== Montez les systèmes de fichiers

Pour monter le  `/hana/shared` systèmes de fichiers lors du démarrage du système à l'aide de  `/etc/fstab` fichier de configuration, ajoutez le  `/hana/shared` système de fichiers vers le  `/etc/fstab` fichier de configuration de chaque hôte.

....
sapcc-hana-tst:/ # cat /etc/fstab
<storage-ip>:/hana_shared /hana/shared nfs rw,vers=3,hard,timeo=600, intr,noatime,nolock 0 0
....

NOTE: Tous les systèmes de fichiers de données et de journaux sont montés via le connecteur de stockage SAP HANA.

Pour monter les systèmes de fichiers, exécutez le `mount –a` commande sur chaque hôte.
