---
sidebar: sidebar 
permalink: bp/hana-aff-nfs-host-setup.html 
keywords: SUSE Linux Enterprise Server, configuration, mount points, LaMa 
summary: 'Toutes les étapes de configuration de l"hôte décrites dans cette section s"appliquent à la fois aux environnements SAP HANA sur des serveurs physiques et à SAP HANA fonctionnant sur VMware vSphere.' 
---
= Configuration de l'hôte
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Toutes les étapes de configuration de l'hôte décrites dans cette section s'appliquent à la fois aux environnements SAP HANA sur des serveurs physiques et à SAP HANA fonctionnant sur VMware vSphere.



== Paramètre de configuration pour SUSE Linux Enterprise Server

D'autres paramètres de noyau et de configuration de chaque hôte SAP HANA doivent être ajustés pour la charge de travail générée par SAP HANA.



=== SUSE Linux Enterprise Server 12 et 15

À partir de SUSE Linux Enterprise Server 12 SP1, le paramètre du noyau doit être défini dans un fichier de configuration dans le `/etc/sysctl.d` répertoire. Par exemple, vous devez créer un fichier de configuration portant le nom `91-NetApp-HANA.conf`.

....
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 16384  16777216
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
sunrpc.tcp_max_slot_table_entries = 128
....

NOTE: Saptune, inclus dans SLES pour les versions de SAP OS, peut être utilisé pour définir ces valeurs. Pour plus d'informations, voir https://launchpad.support.sap.com/#/notes/3024346["Note SAP 3024346"^] (Nécessite une connexion SAP).

....

....


== Paramètres de configuration pour Red Hat Enterprise Linux 7.2 ou version ultérieure

Vous devez ajuster des paramètres de noyau et de configuration supplémentaires sur chaque hôte SAP HANA pour la charge de travail générée par SAP HANA.

À partir de Red Hat Enterprise Linux 7.2, vous devez définir les paramètres du noyau dans un fichier de configuration dans `/etc/sysctl.d` répertoire. Par exemple, vous devez créer un fichier de configuration portant le nom `91-NetApp-HANA.conf`.

....
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 16384  16777216
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
sunrpc.tcp_max_slot_table_entries = 128
....

NOTE: Depuis RedHat Enterprise Linux version 8.6, les paramètres peuvent également être appliqués à l'aide des rôles système RHEL pour SAP (Ansible). Voir https://launchpad.support.sap.com/#/notes/3024346["Note SAP 3024346"^] (Nécessite une connexion SAP).



== Créer les sous-répertoires dans /hana/shared volume


NOTE: Les exemples suivants montrent une base de données SAP HANA avec SID=NF2.

Pour créer les sous-répertoires requis, effectuer l'une des actions suivantes :

* Pour un système à hôte unique, montez le `/hana/shared` volume et créez le `shared` et `usr-sap` sous-répertoires.


....
sapcc-hana-tst-06:/mnt # mount <storage-hostname>:/NF2_shared /mnt/tmp
sapcc-hana-tst-06:/mnt # cd /mnt/tmp
sapcc-hana-tst-06:/mnt/tmp # mkdir shared
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap
sapcc-hana-tst-06:/mnt/tmp # cd ..
sapcc-hana-tst-06:/mnt # umount /mnt/tmp
....
* Pour un système à plusieurs hôtes, montez le `/hana/shared` volume et créez le `shared` et le `usr-sap` sous-répertoires pour chaque hôte.
+
L'exemple de commandes montre un système HANA à hôtes multiples 2+1.



....
sapcc-hana-tst-06:/mnt # mount <storage-hostname>:/NF2_shared /mnt/tmp
sapcc-hana-tst-06:/mnt # cd /mnt/tmp
sapcc-hana-tst-06:/mnt/tmp # mkdir shared
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host1
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host2
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host3
sapcc-hana-tst-06:/mnt/tmp # cd ..
sapcc-hana-tst-06:/mnt # umount /mnt/tmp
....


== Créer des points de montage


NOTE: Les exemples suivants montrent une base de données SAP HANA avec SID=NF2.

Pour créer les répertoires de points de montage requis, procédez comme suit :

* Pour un système à un seul hôte, créez des points de montage et définissez les autorisations sur l'hôte de la base de données.


....
sapcc-hana-tst-06:/ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-06:/ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-06:/ # mkdir -p /hana/shared
sapcc-hana-tst-06:/ # mkdir -p /usr/sap/NF2

sapcc-hana-tst-06:/ # chmod –R 777 /hana/log/NF2
sapcc-hana-tst-06:/ # chmod –R 777 /hana/data/NF2
sapcc-hana-tst-06:/ # chmod -R 777 /hana/shared
sapcc-hana-tst-06:/ # chmod -R 777 /usr/sap/NF2
....
* Pour un système à plusieurs hôtes, créez des points de montage et définissez les autorisations sur tous les hôtes de travail et de secours. L'exemple de commandes suivant est destiné à un système HANA à plusieurs hôtes 2+1.
+
** Hôte du premier employé :




....
sapcc-hana-tst-06:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-06:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-06:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-06:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-06:~ # mkdir -p /hana/shared
sapcc-hana-tst-06:~ # mkdir -p /usr/sap/NF2

sapcc-hana-tst-06:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-06:~ # chmod -R 777 /usr/sap/NF2
....
* Second hôte de travail :


....
sapcc-hana-tst-07:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-07:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-07:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-07:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-07:~ # mkdir -p /hana/shared
sapcc-hana-tst-07:~ # mkdir -p /usr/sap/NF2

sapcc-hana-tst-07:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-07:~ # chmod -R 777 /usr/sap/NF2
....
* Hôte de secours :


....
sapcc-hana-tst-08:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-08:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-08:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-08:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-08:~ # mkdir -p /hana/shared
sapcc-hana-tst-08:~ # mkdir -p /usr/sap/NF2

sapcc-hana-tst-08:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-08:~ # chmod -R 777 /usr/sap/NF2
....


== Montez les systèmes de fichiers

Plusieurs options de montage doivent être utilisées en fonction de la version NFS et de la version ONTAP. Les systèmes de fichiers suivants doivent être montés sur les hôtes :

* `/hana/data/SID/mnt0000*`
* `/hana/log/SID/mnt0000*`
* `/hana/shared`
* `/usr/sap/SID`


Le tableau suivant présente les versions NFS que vous devez utiliser pour les différents systèmes de fichiers des bases de données SAP HANA à un ou plusieurs hôtes.

|===
| Systèmes de fichiers | Hôte unique SAP HANA | Plusieurs hôtes SAP HANA 


| /hana/data/SID/mnt0000* | NFSv3 ou NFSv4 | NFSv4 


| /hana/log/SID/mnt0000* | NFSv3 ou NFSv4 | NFSv4 


| /hana/partagé | NFSv3 ou NFSv4 | NFSv3 ou NFSv4 


| /Usr/sap/SID | NFSv3 ou NFSv4 | NFSv3 ou NFSv4 
|===
Le tableau suivant présente les options de montage pour les différentes versions de NFS et de ONTAP. Les paramètres communs sont indépendants des versions NFS et ONTAP.


NOTE: SAP Lama requiert que le répertoire /usr/sap/SID soit local. Par conséquent, ne montez pas de volume NFS pour /usr/sap/SID si vous utilisez SAP Lama.

Pour NFSv3, vous devez désactiver le verrouillage NFS pour éviter les opérations de nettoyage des verrous NFS en cas de défaillance logicielle ou de serveur.

Avec ONTAP 9, la taille du transfert NFS peut être configurée jusqu'à 1 Mo. En particulier, avec des connexions 40 GbE ou plus rapides vers le système de stockage, vous devez définir la taille de transfert sur 1 Mo pour atteindre les valeurs de débit attendues.

|===
| Paramètre commun | NFSv3 | NFSv4 | Taille du transfert NFS avec ONTAP 9 | Taille du transfert NFS avec ONTAP 8 


| rw, bg, dur, tileo=600, noatime | nfsvers=3,nolock | nfsvers=4.1,verrouiller | rsize=1048576,wsize=262144 | rsize=65536,wsize=65536 
|===

NOTE: Pour améliorer les performances de lecture avec NFSv3, NetApp vous recommande d'utiliser le `nconnect=n` Option de montage, disponible avec SUSE Linux Enterprise Server 12 SP4 ou version ultérieure et RedHat Enterprise Linux (RHEL) 8.3 ou version ultérieure.


NOTE: Des tests de performances ont démontré que `nconnect=4` fournit des résultats de lecture satisfaisants pour les volumes de données. Les écritures de journaux peuvent bénéficier d'un nombre inférieur de sessions, par exemple `nconnect=2`. Les volumes partagés peuvent également bénéficier de l'option « nconnect ». Notez que le premier montage à partir d'un serveur NFS (adresse IP) définit le nombre de sessions utilisées. D'autres montages sur la même adresse IP ne changent pas, même si une valeur différente est utilisée pour nconnect.


NOTE: À partir de ONTAP 9.8 et SUSE SLES15SP2 ou Red Hat RHEL 8.4 ou version ultérieure, NetApp prend également en charge l'option nconnect pour NFSv4.1. Pour plus d'informations, consultez la documentation du fournisseur Linux.


NOTE: Si nconnect est utilisé avec NFSV4.x, le nombre d'emplacements de session NFSv4.x doit être ajusté selon la règle suivante : le nombre d'emplacements de session est égal à <nconnect value> x 64. Sur l'hôte, ceci sera avec l'option d'ajustement de
`echo options nfs max_session_slots=<calculated value> > /etc/modprobe.d/nfsclient.conf` suivi d'un redémarrage. La valeur côté serveur doit également être ajustée, définissez le nombre d'emplacements de session comme décrit dans link:hana-aff-nfs-storage-controller-setup.html#nfs-configuration-for-nfsv4["Configuration NFS pour NFSv4."]

L'exemple suivant montre une base de données SAP HANA à un seul hôte avec SID=NF2 utilisant NFSv3 et une taille de transfert NFS de 1 Mo pour les lectures et 256 Ko pour les écritures. Pour monter les systèmes de fichiers lors du démarrage du système avec `/etc/fstab` fichier de configuration, procédez comme suit :

. Ajoutez les systèmes de fichiers requis à la `/etc/fstab` fichier de configuration.
+
....
sapcc-hana-tst-06:/ # cat /etc/fstab
<storage-vif-data01>:/NF2_data_mnt00001 /hana/data/NF2/mnt00001 nfs rw,nfsvers=3,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-log01>:/NF2_log_mnt00001 /hana/log/NF2/mnt00001 nfs rw,nfsvers=3,hard,timeo=600,nconnect=2,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data01>:/NF2_shared/usr-sap /usr/sap/NF2 nfs rw,nfsvers=3,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data01>:/NF2_shared/shared /hana/shared nfs rw,nfsvers=3,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
....
. Courez `mount –a` pour monter les systèmes de fichiers sur tous les hôtes.


L'exemple suivant montre une base de données SAP HANA à plusieurs hôtes avec SID=NF2 utilisant NFSv4.1 pour les systèmes de fichiers de données et journal et NFS v3 pour le `/hana/shared` et `/usr/sap/NF2` systèmes de fichiers. Une taille de transfert NFS de 1 Mo pour les lectures et 256 Ko pour les écritures est utilisée.

. Ajoutez les systèmes de fichiers requis à la `/etc/fstab` fichier de configuration sur tous les hôtes.
+

NOTE: Le `/usr/sap/NF2` le système de fichiers est différent pour chaque hôte de base de données. L'exemple suivant montre `/NF2_shared/usr-sap-host1`.

+
....
stlrx300s8-5:/ # cat /etc/fstab
<storage-vif-data01>:/NF2_data_mnt00001 /hana/data/NF2/mnt00001 nfs  rw,nfsvers=4.1,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-data02>:/NF2_data_mnt00002 /hana/data/NF2/mnt00002 nfs rw,nfsvers=4.1,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-log01>:/NF2_log_mnt00001 /hana/log/NF2/mnt00001 nfs rw,nfsvers=4.1,hard,timeo=600,nconnect=2,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-log02>:/NF2_log_mnt00002 /hana/log/NF2/mnt00002 nfs rw,nfsvers=4.1,hard,timeo=600,nconnect=2,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-data02>:/NF2_shared/usr-sap-host1 /usr/sap/NF2 nfs rw,nfsvers=3,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data02>:/NF2_shared/shared /hana/shared nfs rw,nfsvers=3,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
....
. Courez `mount –a` pour monter les systèmes de fichiers sur tous les hôtes.

