---
sidebar: sidebar 
permalink: bp/hana-aff-fc-additional-info.html 
keywords:  
summary:  
---
= Où trouver des informations complémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur les informations fournies dans ce document, consultez ces documents et/ou sites web :

* link:../index.html["Solutions logicielles SAP HANA"^]
* link:../backup/hana-dr-sr-pdf-link.html["Reprise après incident de SAP HANA avec la réplication du stockage"^]
* link:../backup/hana-sc-generic-scope.html["SAP HANA : sauvegarde et restauration avec SnapCenter"^]
* link:../lifecycle/sc-copy-clone-introduction.html["Automatisation des opérations de copie et de clonage du système SAP HANA avec SnapCenter"^]
* Centres de documentation NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Matériel de stockage d'entreprise certifié SAP pour SAP HANA
+
https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/["https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/"^]

* Exigences de stockage SAP HANA
+
https://help.sap.com/docs/SAP_HANA_PLATFORM/eb3777d5495d46c5b2fa773206bbfb46/0b15a92d554c4941a452c9ca127f8c70.html^[]]

* Intégration personnalisée des centres de données SAP HANA
+
https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html["https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html"^]

* SAP HANA sur VMware vSphere Wiki
+
https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html["https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html"^]

* Guide des bonnes pratiques de SAP HANA sur VMware vSphere
+
https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper["https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper"^]


