---
sidebar: sidebar 
permalink: bp/saphana-vsphere-fas-aff_pdf_link.html 
keywords: tr-4338, pdf, sap, hana, vmware, vsphere, aff, fas, all flash, fabric attached 
summary: 'Ce document d"architecture de référence aide les clients à concevoir et déployer des solutions SAP HANA à un ou plusieurs hôtes dans des machines virtuelles VMware vSphere et des systèmes de stockage NetApp FAS et AFF (FAS 100 % Flash).' 
---
= Tr-4338 : SAP HANA sur VMware vSphere avec NetApp - FAS et les systèmes FAS 100 % Flash
:allow-uri-read: 
:firstname: : hardbreaks:
:author: : hardbreaks:
:authorinitials: :
:authors: : hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Tobias Brandl, NetApp

Erik Rieger, Bhumik Patel, VMware

Ce document d'architecture de référence aide les clients à concevoir et déployer des solutions SAP HANA à un ou plusieurs hôtes dans des machines virtuelles VMware vSphere et des systèmes de stockage NetApp FAS et AFF (FAS 100 % Flash). Cette architecture de référence est une solution déployée et documentée s'appuyant sur l'expérience des clients VMware et NetApp existants, sur des simulations en conditions réelles et sur les validations du laboratoire d'ingénierie NetApp. Ce document aide les clients à tout au long du cycle de vie du projet, notamment l'évaluation des besoins, la conception de la solution, l'installation et l'administration.

link:https://www.netapp.com/pdf.html?item=/media/17192-tr4338pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17192-tr4338pdf.pdf"]
