---
sidebar: sidebar 
permalink: bp/saphana_aff_nfs_sap_hana_installation_preparations_for_nfsv4.html 
keywords:  
summary: 'NFS version 4 et ultérieure requiert l"authentification utilisateur. Cette authentification peut être réalisée à l"aide d"un outil central de gestion des utilisateurs, tel qu"un serveur LDAP (Lightweight Directory Access Protocol) ou avec des comptes d"utilisateur locaux. Les sections suivantes décrivent comment configurer des comptes utilisateur locaux.' 
---
= Préparation de l'installation de SAP HANA pour NFSv4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NFS version 4 et ultérieure requiert l'authentification utilisateur. Cette authentification peut être réalisée à l'aide d'un outil central de gestion des utilisateurs, tel qu'un serveur LDAP (Lightweight Directory Access Protocol) ou avec des comptes d'utilisateur locaux. Les sections suivantes décrivent comment configurer des comptes utilisateur locaux.

L'utilisateur d'administration `<sidadm>` et le `sapsys` Le groupe doit être créé manuellement sur les hôtes SAP HANA et les contrôleurs de stockage avant que l'installation du logiciel SAP HANA ne commence.



== Hôtes SAP HANA

Si ce n'existe pas déjà, vous devez créer le `sapsys` Group sur l'hôte SAP HANA Sélectionnez un ID de groupe unique qui n'entre pas en conflit avec les ID de groupe existants des contrôleurs de stockage.

L'utilisateur `<sidadm>` Est créée sur l'hôte SAP HANA. Il est nécessaire de choisir un ID unique qui n'entre pas en conflit avec les ID d'utilisateur existants sur les contrôleurs de stockage.

Pour un système SAP HANA à plusieurs hôtes, l'ID utilisateur et groupe doit être identique sur tous les hôtes SAP HANA. Le groupe et l'utilisateur sont créés sur les autres hôtes SAP HANA en copiant les lignes affectées dans `/etc/group` et `/etc/passwd` Depuis le système source vers tous les autres hôtes SAP HANA


NOTE: Le domaine NFSv4 doit être défini sur la même valeur sur tous les serveurs et SVM Linux. Définissez le paramètre de domaine “`Domain = <domain_name>`” dans le fichier `/etc/idmapd.conf` Pour les hôtes Linux.

Activez et démarrez le service NFS idmapd :

....
systemctl enable nfs-idmapd.service
systemctl start nfs-idmapd.service
....

NOTE: Les noyaux Linux les plus récents ne nécessitent pas cette étape. Vous pouvez ignorer les messages d'avertissement en toute sécurité.



== Contrôleurs de stockage

L'ID utilisateur et l'ID de groupe doivent être identiques sur les hôtes SAP HANA et les contrôleurs de stockage. Le groupe et l'utilisateur sont créés en entrant les commandes suivantes sur le cluster de stockage :

....
vserver services unix-group create -vserver <vserver> -name <group name> -id <group id>
vserver services unix-user create -vserver <vserver> -user <user name> -id <user-id> -primary-gid <group id>
....
De plus, définir l'ID du groupe de la racine utilisateur UNIX de la SVM sur 0.

....
vserver services unix-user modify -vserver <vserver> -user root -primary-gid 0
....