---
sidebar: sidebar 
permalink: bp/saphana-ibm-aff-nfs_pdf_link.html 
keywords: tr-4821, pdf, sap, hana, ibm, aff, nfs 
summary: 'IBM Power Systems est conçu pour les workloads stratégiques consommateurs de données, tels que SAP HANA. IBM Power Systems simplifie et accélère les déploiements SAP HANA en fournissant quatre fonctionnalités clés : virtualisation et flexibilité supérieures, provisionnement plus rapide, évolutivité à prix attractif et disponibilité optimisée. La gamme de produits NetApp AFF est certifiée pour une utilisation avec SAP HANA dans le cadre de projets TDI (Tailored Data Center Integration) et complète parfaitement IBM Power Systems. Ce document décrit les meilleures pratiques relatives à la configuration du stockage NAS (NFS) avec NetApp ONTAP et la gamme de produits AFF et les systèmes d"alimentation IBM.' 
---
= Tr-4821 : SAP HANA sur IBM Power Systems et les systèmes NetApp AFF avec NFS
:allow-uri-read: 
:firstname: : hardbreaks:
:author: : hardbreaks:
:authorinitials: :
:authors: : hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Tobias Brandl, NetApp

Carsten Dieterle, IBM

IBM Power Systems est conçu pour les workloads stratégiques consommateurs de données, tels que SAP HANA. IBM Power Systems simplifie et accélère les déploiements SAP HANA grâce à quatre fonctionnalités clés : virtualisation et flexibilité supérieures, provisionnement plus rapide, évolutivité à prix attractif et disponibilité optimisée. La gamme de produits NetApp AFF est certifiée pour une utilisation avec SAP HANA dans le cadre de projets TDI (Tailored Data Center Integration) et complète parfaitement IBM Power Systems. Ce document décrit les meilleures pratiques relatives à la configuration du stockage NAS (NFS) avec NetApp ONTAP et la gamme de produits AFF et les systèmes d'alimentation IBM.

link:https://www.netapp.com/pdf.html?item=/media/19887-TR-4821.pdf["https://www.netapp.com/pdf.html?item=/media/19887-TR-4821.pdf"]
