---
sidebar: sidebar 
permalink: bp/saphana-fas-nfs_i_o_stack_configuration_for_sap_hana.html 
keywords: io, stack, configuration, sap, hana, fas, nfs 
summary: À partir de SAP HANA 1.0 SPS10, SAP a introduit des paramètres pour ajuster le comportement des E/S et optimiser la base de données pour les systèmes de fichiers et de stockage utilisés. 
---
= Configuration de la pile d'E/S pour SAP HANA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
À partir de SAP HANA 1.0 SPS10, SAP a introduit des paramètres permettant d'ajuster le comportement des E/S et d'optimiser la base de données pour les systèmes de fichiers et de stockage utilisés.

Des tests de performances ont été menés par NetApp pour définir les valeurs qui conviennent le mieux. Le tableau suivant répertorie les valeurs optimales issues des tests de performances.

|===
| Paramètre | Valeur 


| max_parallel_io_requests | 128 


| async_read_submit | marche 


| async_write_submit_active | marche 


| async_write_submit_blocks | tous 
|===
Pour les versions SAP HANA 1.0 jusqu'à SPS12, ces paramètres peuvent être définis lors de l'installation de la base de données SAP HANA, comme décrit dans la note SAP https://launchpad.support.sap.com/["2267798 : configuration de la base de données SAP HANA lors de l'installation à l'aide de hdbparam"^].

Alternativement, les paramètres peuvent être définis après l'installation de la base de données SAP HANA à l'aide de `hdbparam` structure.

....
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.max_parallel_io_requests=128
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_active=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_read_submit=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_blocks=all
....
SAP HANA 2.0 et `hdbparam` a été obsolète et les paramètres ont été déplacés vers `global.ini`. Les paramètres peuvent être définis à l'aide des commandes SQL ou SAP HANA Studio. Pour plus de détails, consultez la note SAP https://launchpad.support.sap.com/["2399079: Élimination de hdbparam dans HANA 2"^]. Vous pouvez également définir les paramètres dans global.ini comme indiqué dans le texte suivant :

....
nf2adm@stlrx300s8-6: /usr/sap/NF2/SYS/global/hdb/custom/config> cat global.ini
…
[fileio]
async_read_submit = on
async_write_submit_active = on
max_parallel_io_requests = 128
async_write_submit_blocks = all
…
....
Depuis SAP HANA 2.0 SPS5, le `setParameter.py` le script peut être utilisé pour définir les paramètres corrects :

....
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00/exe/python_support>
python setParameter.py -set=SYSTEM/global.ini/fileio/max_parallel_io_requests=128
python setParameter.py -set=SYSTEM/global.ini/fileio/async_read_submit=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_active=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_blocks=all
....