---
sidebar: sidebar 
permalink: bp/saphana_aff_fc_sap_hana_using_vmware_vsphere.html 
keywords:  
summary:  
---
= SAP HANA avec VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe plusieurs options pour connecter le stockage à des machines virtuelles (VM). La première option consiste à connecter les volumes de stockage avec NFS directement hors du système d'exploitation invité. Cette option est décrite dans le link:http://www.netapp.com/us/media/tr-4435.pdf["SAP HANA sur les systèmes AFF de NetApp avec NFS"].

Les mappages de périphériques bruts (RDM), les data stores FCP ou les data stores VVOL avec FCP sont également pris en charge. Pour les deux options de datastore, un seul volume de données ou de journaux SAP HANA doit être stocké dans le datastore pour des utilisations productives. De plus, les fonctionnalités de sauvegarde et de restauration basées sur les copies Snapshot, orchestrées par SnapCenter, et les solutions reposant sur cela, comme le clonage du système SAP, ne peuvent pas être mises en œuvre.

Pour plus d'informations sur l'utilisation de vSphere avec SAP HANA, consultez les liens suivants :

https://wiki.scn.sap.com/wiki/display/VIRTUALIZATION/SAP+HANA+on+VMware+vSphere["SAP HANA sur VMware vSphere - virtualisation - Wiki communautaire"^]

* http://www.vmware.com/files/pdf/SAP_HANA_on_vmware_vSphere_best_practices_guide.pdf["Meilleures pratiques et recommandations pour les déploiements scale-up de SAP HANA sur VMware vSphere"^]
* http://www.vmware.com/files/pdf/sap-hana-scale-out-deployments-on-vsphere.pdf["Meilleures pratiques et recommandations pour les déploiements en mode scale-out de SAP HANA sur VMware vSphere"^]
* https://launchpad.support.sap.com/["2161991 - instructions de configuration de VMware vSphere - SAP ONE support Launchpad (connexion requise)"^]

