---
sidebar: sidebar 
permalink: bp/saphana_aff_fc_sap_hana_software_installation.html 
keywords: software, installation, 
summary: 'Cette section décrit la préparation nécessaire à l"installation de SAP HANA sur des systèmes à un ou plusieurs hôtes.' 
---
= Installation du logiciel SAP HANA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana_aff_nfs_i_o_stack_configuration_for_sap_hana.html["Précédent : configuration de la pile d'E/S pour SAP HANA."]



== Installation sur un système à hôte unique

L'installation du logiciel SAP HANA ne nécessite aucune préparation supplémentaire pour un système à un hôte unique.



== Installation sur un système à plusieurs hôtes

Avant de commencer l'installation, créez un `global.ini` Fichier permettant d'utiliser le connecteur de stockage SAP pendant le processus d'installation. Le connecteur de stockage SAP monte les systèmes de fichiers requis sur les hôtes worker pendant le processus d'installation. Le `global.ini` le fichier doit être disponible dans un système de fichiers accessible depuis tous les hôtes, tels que `/hana/shared` système de fichiers.

Avant d'installer le logiciel SAP HANA sur un système à plusieurs hôtes, les étapes suivantes doivent être réalisées :

. Ajoutez les options de montage suivantes pour les LUN de données et les LUN de journaux à la `global.ini` fichier :
+
** `relatime` et `inode64` pour le système de fichiers de données et de journaux


. Ajoutez les WWID des partitions de données et de journaux. Les WWID doivent correspondre aux noms d'alias configurés dans le `/etc/multipath.conf` fichier.
+
Le résultat suivant montre un exemple de configuration 2+1 avec plusieurs hôtes dans laquelle l'identifiant système (SID) est SS3.

+
....
stlrx300s8-6:~ # cat /hana/shared/global.ini
[communication]
listeninterface = .global
[persistence]
basepath_datavolumes = /hana/data/SS3
basepath_logvolumes = /hana/log/SS3
[storage]
ha_provider = hdb_ha.fcClient
partition_*_*__prtype = 5
partition_*_data__mountoptions = -o relatime,inode64
partition_*_log__mountoptions = -o relatime,inode64,nobarrier
partition_1_data__wwid = hana-SS3_data_mnt00001
partition_1_log__wwid = hana-SS3_log_mnt00001
partition_2_data__wwid = hana-SS3_data_mnt00002
partition_2_log__wwid = hana-SS3_log_mnt00002
[system_information]
usage = custom
[trace]
ha_fcclient = info
stlrx300s8-6:~ #
....
+
Si le LVM de Linux est utilisé, la configuration requise est différente. L'exemple suivant montre une configuration à plusieurs hôtes 2+1 avec SID=FC5.

+
....
sapcc-hana-tst-03:/hana/shared # cat global.ini
[communication]
listeninterface = .global
[persistence]
basepath_datavolumes = /hana/data/FC5
basepath_logvolumes = /hana/log/FC5
[storage]
ha_provider = hdb_ha.fcClientLVM
partition_*_*__prtype = 5
partition_*_data__mountOptions = -o relatime,inode64
partition_*_log__mountOptions = -o relatime,inode64
partition_1_data__lvmname = FC5_data_mnt00001-vol
partition_1_log__lvmname = FC5_log_mnt00001-vol
partition_2_data__lvmname = FC5_data_mnt00002-vol
partition_2_log__lvmname = FC5_log_mnt00002-vol
sapcc-hana-tst-03:/hana/shared #
Using the SAP hdblcm installation tool, start the installation by running the following command at one of the worker hosts. Use the `addhosts` option to add the second worker (sapcc-hana-tst-04) and the standby host (sapcc-hana-tst-05).
....
+

NOTE: Le répertoire où le a préparé `global.ini` le fichier est stocké avec le `storage_cfg` Option CLI (`-- storage_cfg=/hana/shared`).

+

NOTE: Selon la version du système d'exploitation utilisé, il peut être nécessaire d'installer Python 2.7 avant d'installer la base de données SAP HANA.

+
....
sapcc-hana-tst-03:/mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_LCM_LINUX_X86_64 # ./hdblcm --action=install --addhosts=sapcc-hana-tst-04:role=worker:storage_partion=2,sapcc-hana-tst-05:role:=standby --storage_cfg=/hana(shared/shared


SAP HANA Lifecycle Management - SAP HANA Database 2.00.052.00.1599235305
************************************************************************


Scanning software locations...
Detected components:
    SAP HANA AFL (incl.PAL,BFL,OFL) (2.00.052.0000.1599259237) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_AFL_LINUX_X86_64/packages
    SAP HANA Database (2.00.052.00.1599235305) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_SERVER_LINUX_X86_64/server
    SAP HANA Database Client (2.5.109.1598303414) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_CLIENT_LINUX_X86_64/client
    SAP HANA Smart Data Access (2.00.5.000.0) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/SAP_HANA_SDA_20_LINUX_X86_64/packages
    SAP HANA Studio (2.3.54.000000) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_STUDIO_LINUX_X86_64/studio
    SAP HANA Local Secure Store (2.4.24.0) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HANA_LSS_24_LINUX_X86_64/packages
    SAP HANA XS Advanced Runtime (1.0.130.519) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_RT_10_LINUX_X86_64/packages
    SAP HANA EML AFL (2.00.052.0000.1599259237) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/HDB_EML_AFL_10_LINUX_X86_64/packages
    SAP HANA EPM-MDS (2.00.052.0000.1599259237) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/SAP_HANA_EPM-MDS_10/packages
    GUI for HALM for XSA (including product installer) Version 1 (1.014.1) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACALMPIUI14_1.zip
    XSAC FILEPROCESSOR 1.0 (1.000.85) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACFILEPROC00_85.zip
    SAP HANA tools for accessing catalog content, data preview, SQL console, etc. (2.012.20341) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSAC_HRTT_20/XSACHRTT12_20341.zip
    XS Messaging Service 1 (1.004.10) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACMESSSRV04_10.zip
    Develop and run portal services for customer apps on XSA (1.005.1) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACPORTALSERV05_1.zip
    SAP Web IDE Web Client (4.005.1) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSAC_SAP_WEB_IDE_20/XSACSAPWEBIDE05_1.zip
    XS JOB SCHEDULER 1.0 (1.007.12) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACSERVICES07_12.zip
    SAPUI5 FESV6 XSA 1 - SAPUI5 1.71 (1.071.25) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACUI5FESV671_25.zip
    SAPUI5 SERVICE BROKER XSA 1 - SAPUI5 Service Broker 1.0 (1.000.3) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACUI5SB00_3.zip
    XSA Cockpit 1 (1.001.17) in /mnt/sapcc-share/software/SAP/HANA2SP5-52/DATA_UNITS/XSA_CONTENT_10/XSACXSACOCKPIT01_17.zip


SAP HANA Database version '2.00.052.00.1599235305' will be installed.

Select additional components for installation:
  Index | Components | Description
  ---------------------------------------------------------------------------------------------
  1     | all        | All components
  2     | server     | No additional components
  3     | client     | Install SAP HANA Database Client version 2.5.109.1598303414
  4     | lss        | Install SAP HANA Local Secure Store version 2.4.24.0
  5     | studio     | Install SAP HANA Studio version 2.3.54.000000
  6     | smartda    | Install SAP HANA Smart Data Access version 2.00.5.000.0
  7     | xs         | Install SAP HANA XS Advanced Runtime version 1.0.130.519
  8     | afl        | Install SAP HANA AFL (incl.PAL,BFL,OFL) version 2.00.052.0000.1599259237
  9     | eml        | Install SAP HANA EML AFL version 2.00.052.0000.1599259237
  10    | epmmds     | Install SAP HANA EPM-MDS version 2.00.052.0000.1599259237

Enter comma-separated list of the selected indices [3]: 2,3
Enter Installation Path [/hana/shared]:
Enter Local Host Name [sapcc-hana-tst-03]:
....
. Vérifiez que l'outil d'installation a installé tous les composants sélectionnés sur tous les hôtes de travail et de secours.


link:saphana_aff_fc_adding_additional_data_volume_partitions_for_sap_hana_single-host_systems.html["Ensuite, ajout de partitions de volume de données supplémentaires pour les systèmes SAP HANA à un seul hôte."]
