---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-additional-info.html 
keywords: tr4667, 4667, SAP HANA, cloning, system refresh 
summary: 'Les solutions NetApp pour l"optimisation de la gestion du cycle de vie SAP sont intégrées aux outils de gestion du cycle de vie et de la base de données SAP HANA. Elles combinent une protection des données intégrée aux applications efficace avec le provisionnement flexible des systèmes de test SAP.' 
---
= Où trouver des informations supplémentaires et l'historique des versions
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur les informations fournies dans ce document, consultez ces documents et/ou sites web :

* link:../index.html["Solutions SAP Business application et SAP HANA Database (netapp.com)"]
* link:../backup/hana-sc-generic-scope.html["SAP HANA : sauvegarde et restauration avec SnapCenter"]
* link:../bp/hana-aff-fc-introduction.html["SAP HANA sur NetApp All Flash FAS Systems avec protocole Fibre Channel"]
* link:../bp/hana-aff-nfs-introduction.html["SAP HANA sur NetApp All Flash FAS Systems avec NFS"]
* link:../backup/fsxn-overview.html["SAP HANA sur Amazon FSX pour NetApp ONTAP - sauvegarde et restauration avec SnapCenter"]
* link:lama-ansible-introduction.html["Intégration de NetApp dans la gestion de l'environnement SAP avec Ansible"]
* link:libelle-sc-overview.html["Automatisation des opérations de copie du système SAP avec Libelle SystemCopy (netapp.com)"]
* link:../briefs/sap-alpaca-automation.html["Automatisation de la copie, de l'actualisation et du clonage des workflows du système SAP avec ALPAGA et NetApp SnapCenter"]
* link:../briefs/sap-avantra-automation.html["Automatisation des workflows de copie, d'actualisation et de clonage du système SAP avec Avantra et NetApp SnapCenter"]


[cols="21%,20%,59%"]
|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Février 2018 | Version initiale. 


| Version 2.0 | Février 2021  a| 
Réécriture complète couvrant SnapCenter 4.3 et amélioration des scripts d'automatisation. + Nouvelle description de workflow pour les opérations d'actualisation du système et de clonage du système.



| Version 3.0 | Mai 2022 | Adapté au workflow modifié avec SnapCenter 4.6 P1 


| Version 4.0 | Juillet 2024  a| 
Il couvre les systèmes NetApp sur site, FSX pour ONTAP et Azure NetApp Files + les nouvelles opérations SnapCenter 5.0 montent et démontent lors de la création et de la suppression de clones + étapes spécifiques supplémentaires pour SAN Fibre Channel + étapes spécifiques supplémentaires pour Azure NetApp Files + script adapté et simplifié `sc-system-refresh` + étapes requises incluses pour l'activation de SAP HANA chiffrement de volume



| Version 4.1 | Février 2026 | Ajout des étapes requises pour le chiffrement HANA et le stockage sécurisé local SAP LSS 
|===