---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-supported-infrastructure.html 
keywords: tr4667, 4667, SAP HANA, cloning, system refresh 
summary: 'Les solutions NetApp pour l"optimisation de la gestion du cycle de vie SAP sont intégrées aux outils de gestion du cycle de vie et de la base de données SAP HANA. Elles combinent une protection des données intégrée aux applications efficace avec le provisionnement flexible des systèmes de test SAP.' 
---
= Infrastructure et scénarios pris en charge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce document présente les scénarios d'actualisation et de clonage des systèmes SAP HANA s'exécutant sur des systèmes NetApp sur site, sur des systèmes Amazon FSX pour NetApp ONTAP et sur Azure NetApp Files. Toutefois, certaines fonctionnalités et certains scénarios ne sont pas disponibles sur chaque plateforme de stockage. Le tableau ci-dessous récapitule les configurations prises en charge.

Ce document utilise un paysage SAP HANA s'exécutant sur des systèmes NetApp sur site avec le protocole de stockage NFS. La plupart des étapes de workflow sont identiques sur les différentes plates-formes et, en cas de différences, elles sont mises en évidence dans ce document.

[cols="25%,25%,25%,25%"]
|===
|  | *Systèmes NetApp sur site* | *AWS FSX pour NetApp ONTAP* | *Azure NetApp Files* 


| Protocole de stockage et système de fichiers | Bare metal : NFS, FC avec XFS VMware : montages NFS dans l'invité, FC avec VMDK et XFS | NFS | NFS 


| Clone dynamique (FlexClone) | Oui. | Oui. | Oui, mais pas intégré dans SnapCenter 


| Opération de séparation des clones | Oui. | Oui. | Oui, mais pas intégré dans SnapCenter 


| Clonage depuis le stockage primaire | Oui. | Oui. | Oui. 


| Clonage à partir d'une sauvegarde hors site | Oui. | Oui. | Oui, restaurer sur un nouveau volume à partir de la sauvegarde ANF 


| Clonage sur le site de reprise après incident | Oui. | Oui. | Oui, mais pas intégré dans SnapCenter 
|===
Des informations supplémentaires sur les opérations de mise à jour du système SAP pour HANA avec VMware VMFS et les systèmes NetApp ASAr2 sont disponibles à  https://docs.netapp.com/us-en/netapp-solutions-sap/backup/hana-sc-vmfs-asar2sap-refresh.html["Actualisation du système SAP"].
