---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-additional-info.html 
keywords: tr4667, 4667, SAP HANA, cloning, system refresh 
summary: 'Les solutions NetApp pour l"optimisation de la gestion du cycle de vie SAP sont intégrées aux outils de gestion du cycle de vie et de la base de données SAP HANA. Elles combinent une protection des données intégrée aux applications efficace avec le provisionnement flexible des systèmes de test SAP.' 
---
= Où trouver des informations supplémentaires et l'historique des versions
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur les informations fournies dans ce document, consultez ces documents et/ou sites web :

* link:../index.html["Solutions SAP Business application et SAP HANA Database (netapp.com)"]
* link:../backup/hana-br-scs-overview.html["Tr-4614 : sauvegarde et restauration SAP HANA avec SnapCenter"]
* link:../bp/hana-aff-fc-introduction.html["Tr-4436 : SAP HANA sur les systèmes FAS 100 % Flash de NetApp avec protocole Fiber Channel"]
* link:../bp/hana-aff-nfs-introduction.html["Tr-4435 : SAP HANA sur les systèmes FAS 100 % Flash de NetApp avec NFS"]
* link:../backup/fsxn-overview.html["Tr-4926 : SAP HANA sur Amazon FSX pour NetApp ONTAP - sauvegarde et restauration avec SnapCenter"]
* link:lama-ansible-introduction.html["Tr-4953 : intégration de la gestion paysage SAP avec Ansible de NetApp"]
* link:libelle-sc-overview.html["Tr-4929 : automatisation des opérations de copie de systèmes SAP avec libelle SystemCopy (netapp.com)"]
* link:../briefs/sap-alpaca-automation.html["Automatisation de la copie, de l'actualisation et du clonage des workflows du système SAP avec ALPAGA et NetApp SnapCenter"]
* link:../briefs/sap-avantra-automation.html["Automatisation des workflows de copie, d'actualisation et de clonage du système SAP avec Avantra et NetApp SnapCenter"]


[cols="21%,20%,59%"]
|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Février 2018 | Version initiale. 


| Version 2.0 | Février 2021  a| 
Réécriture complète couvrant SnapCenter 4.3 et amélioration des scripts d'automatisation. + Nouvelle description de workflow pour les opérations d'actualisation du système et de clonage du système.



| Version 3.0 | Mai 2022 | Adapté au workflow modifié avec SnapCenter 4.6 P1 


| Version 4.0 | Juillet 2024  a| 
Il couvre les systèmes NetApp sur site, FSX pour ONTAP et Azure NetApp Files + les nouvelles opérations SnapCenter 5.0 montent et démontent lors de la création et de la suppression de clones + étapes spécifiques supplémentaires pour SAN Fibre Channel + étapes spécifiques supplémentaires pour Azure NetApp Files + script adapté et simplifié `sc-system-refresh` + étapes requises incluses pour l'activation de SAP HANA chiffrement de volume

|===